### PR TITLE
added Comment and detailed FCR info

### PR DESCRIPTION
**Pull request by flopp999**

### CODE REVIEW

**Comment by faanskit** [comment]
Did you commit the __init__.py? I can only see examples.py, README.md and pyproject.toml.
Also, please fix Flake8 issues (x3)reported.

**Comment by flopp999** [comment]
> Did you commit the **init**.py? I can only see examples.py, README.md and pyproject.toml. Also, please fix Flake8 issues (x3)reported.

Sorry, I have done changes there but forgot to upload, good catch :)

**Comment by flopp999** [comment]
More to come so not needed to approve now

**Comment by flopp999** [comment]
@faanskit ops I merged it now. I thought I only updated and sent the changes to complete the PR

**Pull request merged**
